# COCO/YOLO-style dataset config for m2cai16-tool-locations
train: /content/drive/MyDrive/yolov8_train/m2cai16-tool-locations_YOLO/train
test: /content/drive/MyDrive/yolov8_train/m2cai16-tool-locations_YOLO/test
val: /content/drive/MyDrive/yolov8_train/m2cai16-tool-locations_YOLO/val

nc: 7
names: ['Grasper','Bipolar','Hook','Scissors','Clipper','Irrigator','Specimen Bag']

